name: 'Saludo desde Docker'
description: 'Hace un saludo desde el contenedor'
inputs:
  quien:
    description: 'Para quien es el saludo'
    required: true
    deafult: 'todos'
outputs:
  hora:
    description: 'la hora del saludito'
runs:
   using: 'Docker'
   image: 'Dockerfile'
   args:
     - ${{ inputs.quien }}
