name: 'Ejecutar Docker'
on: push
jobs:
  saludar:
      runs-on: ubuntu-latest
      name: 'tarea para saludarme 2'
      steps:
       - name: 'ejecutar la accions del docker'
         id: hola
         uses: Deyber13013/ina-docker-mg@main
         with:
            quien: 'Lucho'
       - name: 'Mostrar la hora obtenida'
         run: echo "la hora obtenida fue ${{ steps.hola.outputs.hora }}"
